### PR TITLE
make environment.yml linux compatible

### PR DESCRIPTION
**Pull request by steve98654**

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
Thanks for doing this. Sorry it took so long, got preoccupied with a bunch of other things going on.

**Comment by steve98654** [comment]
Hi Takuya,

I was looking more at your example a few days ago and was wondering if you
know how to color regions in individual layers different colors

Specifically, I was hoping to create a heat map where values of each region
are colored according to a given variable.  For example, can one color by
the value of your Num_LEP variable where the higher the variable the darker
the color and the smaller the lighter?

I tried to edit your code to do this but have not been successful so far
... and recommendations would be much appreciated!

Steve

**Comment by ConnectedSystems** [comment]
Hi @steve98654 

Looks like you could modify the answer given [here](https://stackoverflow.com/a/28752903/2694952) to do what you want. There's various other ways to do it though.

Let me know if you still need help (with code if possible), and I'll try to help if/when I can.

**Comment by steve98654** [comment]
Hey Takuya, 

Thanks for the response, but it is not clear to me how to integrate this into your example.  

If you have time to create an example where you color code each region for a specific layer by a value of a variable specific to that region (e.g. population or your Num_LEP variable), it would be much appreciated!  It is the last step in a visualization I am working on for a project.

Best,
Steve

**Comment by ConnectedSystems** [comment]
Hi @steve98654 

Have a look at the updated example in the `m-dev` branch.

I also updated the Windows environment file to use a more recent version of Dash. 
Would you be able to do the same for *nix and submit a PR?

**Comment by steve98654** [comment]
Thanks for the example, it works great.  This script runs in the same venv
that I had lasttime.  Will try to update dash to match your windows version
in a linux environment and submit a PR soon!

Thanks again,
Steve

**Pull request merged**
